name: Execute monthly security scan

env:
  TEAM_TO_NOTIFY: '@here'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  security:
    name: Run Security Scans
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Service
        uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Setup
        run: make setup
      - name: Run Security Audit
        run: make scan

  notify:
    name: Notify Chat
    if: ${{ always() && needs.security.result == 'failure' }}
    runs-on: ubuntu-20.04
    needs: [ security ]
    steps:
      - name: Notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#ff0000'
          SLACK_LINK_NAMES: true
          SLACK_TITLE: Security scan failed for ${{ github.repository }}
          SLACK_MESSAGE: ${{ env.TEAM_TO_NOTIFY }}

